export const SHOPPING_GET_PRODUCT_LIST_INITIATED = 'SHOPPING_GET_PRODUCT_LIST_INITIATED',
    SHOPPING_GET_PRODUCT_LIST_SUCCEEDED = 'SHOPPING_GET_PRODUCT_LIST_SUCCEEDED',
    SHOPPING_GET_PRODUCT_LIST_FAILED = 'SHOPPING_GET_PRODUCT_LIST_FAILED',
    SHOPPING_SET_PRODUCT_SELECTED = 'SHOPPING_SET_PRODUCT_SELECTED',
    SHOPPING_SET_PRODUCT_FILTER = 'SHOPPING_SET_PRODUCT_FILTER',
    SHOPPING_KAFKA_PRODUCT_CALL = 'SHOPPING_KAFKA_PRODUCT_CALL';