export const GET_ORDER_HISTORY_VERIFY_INITIATED = 'GET_ORDER_HISTORY_VERIFY_INITIATED';
export const GET_ORDER_HISTORY_VERFIY_SUCCEEDED = 'GET_ORDER_HISTORY_VERIFY_SUCCEEDED';
export const GET_ORDER_HISTORY_REQUEST_FAILED = 'GET_ORDER_HISTORY_REQUEST_FAILED';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';