export const 
    PURCHASE_SUMMARY_CHANGE_ADDRESS = 'PURCHASE_SUMMARY_CHANGE_ADDRESS',
    PURCHASE_SUMMARY_INCREMENT_ITEMS = 'PURCHASE_SUMMARY_INCREMENT_ITEMS',
    PURCHASE_SUMMARY_DECREMENT_ITEMS = 'PURCHASE_SUMMARY_DECREMENT_ITEMS',
    PURCHASE_SUMMARY_UPDATE_TOTAL = 'PURCHASE_SUMMARY_UPDATE_TOTAL';