export const P2P_AMOUNT_CHANGED = 'P2P_AMOUNT_CHANGED',
    P2P_DESCRIPTION_CHANGED = 'P2P_DESCRIPTION_CHANGED',
    P2P_PAYMENT_INITIATED = 'P2P_PAYMENT_INITIATED',
    P2P_PAYMENT_SUCCEEDED = 'P2P_PAYMENT_SUCCEEDED',
    P2P_PAYMENT_FAILED = 'P2P_PAYMENT_FAILED';