export const WALLET_TO_WALLET_DETAILS = 'WALLET_TO_WALLET_DETAILS',
    ON_SCAN_START = 'ON_SCAN_START',
    ON_SCAN_SUCCESS = 'ON_SCAN_SUCCESS',
    ON_SCAN_FAILURE = 'ON_SCAN_FAILURE',
    ON_PAY_START = 'ON_PAY_START',
    ON_PAY_SUCCESS = 'ON_PAY_SUCCESS',
    ON_PAY_FAILURE = 'ON_PAY_FAILURE';