# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LEFA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LEFA

  pod 'Firebase/Core'

  target 'LEFA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LEFATests' do
    inherit! :search_paths
    # Pods for testing
  end

end
