export const 
    PAYMENT_OPTIONS_CHANGE_MODE = 'PAYMENT_OPTIONS_CHANGE_MODE',
    PAYMENT_OPTIONS_PROCESS_SALE_INITIATED = 'PAYMENT_OPTIONS_PROCESS_SALE_INITIATED',
    PAYMENT_OPTIONS_PROCESS_SALE_FAILURE = 'PAYMENT_OPTIONS_PROCESS_SALE_FAILURE',
    PAYMENT_OPTIONS_PROCESS_SALE_SUCCESS = 'PAYMENT_OPTIONS_PROCESS_SALE_SUCCESS',
    PAYMENT_OPTIONS_PROCESS_SET_ORDER_NUMBER = 'PAYMENT_OPTIONS_PROCESS_SET_ORDER_NUMBER';