export const 
    CLEAR_LOGIN_DETAILS = 'CLEAR_LOGIN_DETAILS',
    LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE',
    LOGIN_EMAIL_CHANGE = 'LOGIN_EMAIL_CHANGE',
    LOGIN_SUBMIT_BEGIN = 'LOGIN_SUBMIT_BIGIN',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE',
    LOGIN_WITH_NEDBANK_MONEY_BEGIN = 'LOGIN_WITH_NEDBANK_MONEY_BEGIN',
    LOGIN_WITH_NEDBANK_MONEY_SUCCESS = 'LOGIN_WITH_NEDBANK_MONEY_SUCCESS',
    LOGIN_WITH_NEDBANK_MONEY_FAILURE = 'LOGIN_WITH_NEDBANK_MONEY_FAILURE',
    LOGIN_GET_USER_INFO_BY_USERNAME_BEGIN = 'LOGIN_GET_USER_INFO_BY_USERNAME_BEGIN',
    LOGIN_GET_USER_INFO_BY_USERNAME_SUCCESS = 'LOGIN_GET_USER_INFO_BY_USERNAME_SUCCESS',
    LOGIN_GET_USER_INFO_BY_USERNAME_FAILURE = 'LOGIN_GET_USER_INFO_BY_USERNAME_FAILURE',
    LOGIN_OFF = 'LOGIN_OFF';